### PR TITLE
[Whitepaper] Fixing typos and cleaning up grammar

### PR DESCRIPTION
**Pull request by xmulligan**

### CODE REVIEW

**Comment by ASalkever** [comment]
Hi, @xmulligan - thanks for catching some of the typos. Most of the comma changes you want to make are changing from non-Oxford to Oxford commas. CNCF style is not to use Oxford comman. In other places, the changes are moving from British to American English, which we want to do.I will merge the changes but will go back and revert the commas in a separate PR. Thanks.

**Comment by xmulligan** [comment]
Thanks, would like to respectfully disagree with not using the Oxford comma though ;p

**Comment by ASalkever** [comment]
@xmulligan - you'll have to take that up with @dankohn ;)

**Comment by ASalkever** [comment]
I stand corrected. We do use Oxford commas. So most of your changes are awesome. Thank you @xmulligan. I'll do a final scrub as well as we get to publication.

**Pull request merged**
