### PR TITLE
[Whitepaper] Small changes in 1.3.3 and 1.5.4

### PR DESCRIPTION
**Pull request by petorre**
Few small changes proposed:
- 1.3.3 "Linux" -> "Host OS" as not all HostOS must be Linux. Mention basic libraries requirements.
- 1.5.4. To "VNFs built on OpenStack and VMware" added "VMs".

And signing.

### CODE REVIEW

**Comment by jeffsaelens** [comment]
On the first point, I haven't seen any truly performant networking use cases running in Unix or Windows. Can you point me to some examples? Curious to see what folks in these different communities have been doing from an acceleration standpoint.

**Comment by petorre** [comment]
> 
> 
> On the first point, I haven't seen any truly performant networking use cases running in Unix or Windows. Can you point me to some examples? Curious to see what folks in these different communities have been doing from an acceleration standpoint.

Like ESXi as deployed HostOS running VMs with pods or new "k8s embedded" [blog](https://blogs.vmware.com/cloudnative/2020/03/17/vsphere-7-and-tanzu-kubernetes-grid-powerful-platform-for-architecting-modern-apps/).
Also I was not thinking only about dataplane-intensive.
Now looking online on DPDK.org I see Getting Started Guides for FreeBSD and Windows. Those and several UNIXes also have SR-IOV.
Still, re-reading the chapter it feels that assumption was only bare metal containers so "HostOS" does not mean hypervisor running GuestOS with containers which is how many vendors offer NFV solutions.

**Comment by jeffsaelens** [comment]
Much appreciated, I'm going to poke around and do some reading on the UNIX implementations.

**Comment by petorre** [comment]
> 
> 
> Suggest changing phrasing:
> 
> > As containers are agnostic to the distribution of Host OS they are hosted on
> 
>     * remove "they are hosted on"
> 
>     * use something other than distribution

Is "type of Host OS they are running on" good?

**Pull request merged**
